# Generated by Django 2.2.12 on 2021-08-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(choices=[('Franko', 'Franko'), ('Mebrat', 'Mebrat'), ('POSTA', 'POSTA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank',
            field=models.CharField(choices=[('AWASH', 'AWASH'), ('abysinea', 'abysinea'), ('CBE', 'CBE'), ('Zemzem', 'Zemzem')], max_length=35),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Watch', 'Watch')], max_length=200, null=True),
        ),
    ]
