# Generated by Django 2.2.12 on 2021-08-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0002_auto_20210819_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Customer')),
                ('product', models.ManyToManyField(to='supermarket.Product')),
            ],
        ),
    ]
